Update Makefile
0o-de-lally/libra-framework pull request #9
Opened 2024-03-17 02:52 UTC by sirouk

prepped and ready

2024-03-17 19:28 UTC, 0o-de-lally requested changes

2024-03-17 19:28 UTC, 0o-de-lally commented on tools/rescue/Makefile
> +VALS_FILE=~/libra-framework/tools/rescue/fixtures/fork/validators.json
Can you make this into a path using variables please

2024-03-17 19:28 UTC, 0o-de-lally commented on tools/rescue/Makefile
> +	cd ${DATA_PATH}/ && \
use Makefile working directory instead of `cd` and inline commands

2024-03-18 04:47 UTC, sirouk commented on tools/rescue/Makefile
> +VALS_FILE=~/libra-framework/tools/rescue/fixtures/fork/validators.json
Done, needs review.

2024-03-18 04:47 UTC, sirouk commented on tools/rescue/Makefile
> +	cd ${DATA_PATH}/ && \
Done, needs review.

2024-03-29 22:31 UTC, merged